version: "3.8"

services:
  web:
    image: sonhipp/phukienoto:v1.0.0
    container_name: phukienoto-web
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./public/uploads:/app/public/uploads
    env_file:
      - .env
    environment:
      NODE_ENV: production
